name:                 hgg-svg
version:              0.1.0.0
visibility:           public
id:                   hgg-svg-0.1.0.0-inplace
key:                  hgg-svg-0.1.0.0-inplace
license:              BSD-3-Clause
copyright:            2026 Hgg
maintainer:           frenzieddoll@gmail.com
author:               frenzieddoll
synopsis:             SVG backend for hgg (純 Haskell、 OSS の主用途)
description:
    ブラウザ非依存の SVG 出力 backend。 OSS ユーザの大半がこの package を経由
    して plot を生成する想定。 Phase 26 §B の実体。

category:             Graphics
abi:                  inplace
exposed:              True
exposed-modules:      Hgg.Plot.Backend.SVG Hgg.Plot.Quick
import-dirs:
    /home/toshiaki/projects/hgg/dist-newstyle/build/x86_64-linux/ghc-9.6.7/hgg-svg-0.1.0.0/build

library-dirs:
    /home/toshiaki/projects/hgg/dist-newstyle/build/x86_64-linux/ghc-9.6.7/hgg-svg-0.1.0.0/build

library-dirs-static:
    /home/toshiaki/projects/hgg/dist-newstyle/build/x86_64-linux/ghc-9.6.7/hgg-svg-0.1.0.0/build

dynamic-library-dirs:
    /home/toshiaki/projects/hgg/dist-newstyle/build/x86_64-linux/ghc-9.6.7/hgg-svg-0.1.0.0/build

data-dir:             /home/toshiaki/projects/hgg/hgg-svg/.
hs-libraries:         HShgg-svg-0.1.0.0-inplace
depends:
    base-4.18.3.0 hgg-core-0.1.0.0-inplace hgg-frame-0.1.0.0-inplace
    text-2.0.2
    vector-0.13.2.0-44a212992f25233ccd712d356a555b0bdaf449d50bb377a3a6ccef858aa7148f

haddock-interfaces:
    /home/toshiaki/projects/hgg/dist-newstyle/build/x86_64-linux/ghc-9.6.7/hgg-svg-0.1.0.0/doc/html/hgg-svg/hgg-svg.haddock

haddock-html:
    /home/toshiaki/projects/hgg/dist-newstyle/build/x86_64-linux/ghc-9.6.7/hgg-svg-0.1.0.0/doc/html/hgg-svg
